### ISSUE TITLE
清理旧代码与无效代码

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#103]
### Subject of the feature

清理旧代码与无效代码

### Problem

代码从之前的版本重构修改，里面遗留了很多陈旧的代码，很多不再使用的代码只是简单的注释掉，还有些相同功能的代码放在多个文件中，这会给后面开发的人造成很大的困惑

### Expected behaviour

代码干净整洁

**Comment by likui628** [comment]
PR #107 清理了layouts包内的代码

**Comment by aonoa** [comment]
@likui628  `packages/grid-layouts` 可以删除吗

**Comment by aonoa** [comment]
> > @likui628 `packages/grid-layouts` 可以删除吗
> 
> 看样子可以删，你可以提个PR让 @jinmao88 review

我昨天问过了，他说可能还会有别人用

**Comment by likui628** [comment]
那就先别动了，就当不存在好了

**Comment by likui628** [comment]
这个项先关了
