### ISSUE TITLE
DynamicTags 控件导致页面卡死

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#109]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

[demo 表单页面](https://vben.mufei88.com/#/demo/form) DynamicTags 控件，先添加，后删除，在添加会导致整个页面卡死

### Reproduction
https://vben.mufei88.com/#/demo/form DynamicTags
1. 添加标签
2. 删除标签
3. 添加标签  

页面会卡死

**Comment by likui628** [comment]
我试了不会

**Comment by aonoa** [comment]
> 我试了不会

![image](https://github.com/vbenjs/vben3/assets/32682251/ca645f5e-3146-4f6f-b955-baff2fc0c72b)

**Comment by aonoa** [comment]
![image](https://github.com/vbenjs/vben3/assets/32682251/49226c65-2331-41b5-b8e7-abd511ff47fe)

**Comment by likui628** [comment]
[Vue warn]: Maximum recursive updates exceeded in component <index>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

https://github.com/vbenjs/vben3/blob/e36a24daa18471785320961611992a6ef05fe0a0/packages/vbenComponents/src/form/src/Form.vue#L145

@aonoa 问题应该是这里了
