### ISSUE TITLE
导航栏模式中，在非“左侧菜单混合模式“中能选择“固定展开菜单“

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#111]
导航栏模式中，在非“左侧菜单混合模式“中能选择“固定展开菜单“，且，在其他模式中选择打开“固定展开菜单“，然后切换导航栏模式为“左侧菜单混合模式“，左侧菜单栏中为空白，需点击一下菜单图标才正常
![image](https://github.com/vbenjs/vben3/assets/32682251/16521a4f-2996-4078-b3e9-6e678b8e2af0)

**Comment by likui628** [comment]
预期结果：

1. “左侧菜单混合”模式允许设置“固定展开菜单”
2. 其它模式下不允许设置

**Comment by aonoa** [comment]
> 预期结果：
> 
> 1. “左侧菜单混合”模式允许设置“固定展开菜单”
> 2. 其它模式下不允许设置

是的是的，预期行为我参考的 https://vben.vvbin.cn/

**Comment by aonoa** [comment]
在 “左侧菜单混合模式” 中 选中/取消选中“固定展开菜单”
![image](https://github.com/vbenjs/vben3/assets/32682251/88d35f0a-1680-4485-a7d2-726da6d379ef)

**Comment by aonoa** [comment]
点击菜单的展开过程的动画效果
![image](https://github.com/vbenjs/vben3/assets/32682251/7c00447d-0269-4218-8b2f-d29242e91ebe)
