### ISSUE TITLE
“分割菜单”功能不正确

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#115]
### vben3
<img width="617" alt="1" src="https://github.com/vbenjs/vben3/assets/90845831/cb18adc1-4e16-4526-9600-c205527d597d">

### vben2
<img width="557" alt="2" src="https://github.com/vbenjs/vben3/assets/90845831/1adcf915-564e-4f1d-bec8-affb26e375c5">

**Comment by aonoa** [comment]
顶部菜单混合模式，分割菜单，选择表单，左测消失
![image](https://github.com/vbenjs/vben3/assets/32682251/bcdafe43-88d7-4ed3-9f27-723829ef48a4)
实际应该是下面这样才对
![image](https://github.com/vbenjs/vben3/assets/32682251/cee82d5a-2a2e-47c8-a3df-bc7c162f209a)

**Comment by jinmao88** [comment]
递归函数有点问题

**Comment by jinmao88** [comment]
修了
