### ISSUE TITLE
“侧边菜单，拖拽调整宽度”无效

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#118]
![image](https://github.com/vbenjs/vben3/assets/90845831/7bf06f8a-97b5-4a41-b785-224fb3adf565)
无法拖拽调整左侧菜单宽度

**Comment by aonoa** [comment]
在左侧菜单混合模式下，鼠标移动到这个线位置的时候，会触发展开菜单栏的折叠

**Comment by likui628** [comment]
这个功能没有效

**Comment by aonoa** [comment]
> 这个功能没有效

这个线这里会有bug，把这个issue关了我再新开一个?

**Comment by jinmao88** [comment]
说清楚啥bug呀

**Comment by aonoa** [comment]
> 在左侧菜单混合模式下，鼠标移动到该线位置的时候，会触发展开菜单栏的折叠

主要还是这根线的问题，在左侧菜单混合模式下，鼠标移动到该线位置的时候，会触发展开菜单栏的折叠

[录屏 2023年10月26日 14时08分49秒.webm](https://github.com/vbenjs/vben3/assets/32682251/40010912-ee35-4be2-ae6a-8251367a8cd1)

**Comment by likui628** [comment]
这个issue原来是表示，没法拖拽调整sidebar的宽度。

**Comment by aonoa** [comment]
> 这个issue原来是表示，没法拖拽调整sidebar的宽度。

所以我才问要不要新开一个issue反馈

**Comment by aonoa** [comment]
> 你视频里不是自动关闭菜单面板的问题么

是，但是不完全是，主要是这个录屏看不到鼠标位置
