### ISSUE TITLE
"折叠菜单显示名称"无效

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#119]
![image](https://github.com/vbenjs/vben3/assets/90845831/269733a5-897c-43e5-ad66-17269229f131)

**Comment by aonoa** [comment]
https://www.naiveui.com/zh-CN/light/components/menu naive好像不支持

**Comment by jinmao88** [comment]
When folded, the name is displayed in the same way as the blend menu on the left, which doesn't feel necessary
The component itself is not supported
