### ISSUE TITLE
在 “左侧菜单混合模式” 中 选中/取消选中“固定展开菜单”

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#204]
在 “左侧菜单混合模式” 中 选中/取消选中“固定展开菜单”，菜单栏出现了空白
![image](https://github.com/vbenjs/vben3/assets/32682251/8ab15793-8edb-4bc4-8672-44899beeab95)

**Comment by pzzyf** [comment]
对比了vben2，这边是固定展开菜单的二级路由没做
