### ISSUE TITLE
mock报错导致开发环境退出

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#208]
开发环境运行时调用mock接口 /basic-api/demo/operator，报错

> TypeError: module.require is not a function
> @apps/admin:dev:     at Object.dataImage (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:1480:34)
> @apps/admin:dev:     at Object.placeholder (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:592:34)
> @apps/admin:dev:     at Object.string (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:456:33)
> @apps/admin:dev:     at Object.Handler.gen (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:209:30)
> @apps/admin:dev:     at Object.object (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:380:46)
> @apps/admin:dev:     at Object.Handler.gen (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:209:30)
> @apps/admin:dev:     at Object.array (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:248:30)
> @apps/admin:dev:     at Object.Handler.gen (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:209:30)
> @apps/admin:dev:     at Object.object (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:380:46)
> @apps/admin:dev:     at Object.Handler.gen (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:209:30)
> @apps/admin:dev:     at Object.Mock.mock (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\mockjs@1.1.0\node_modules\mockjs\dist\mock.js:106:25)
> @apps/admin:dev:     at middleware (C:\Users\likui\IdeaProjects\vben3\node_modules\.pnpm\vite-plugin-mock@2.9.6_mockjs@1.1.0_rollup@4.1.4_vite@4.5.0\node_modules\vite-plugin-mock\dist\index.js:123:49)
> @apps/admin:dev:     at runMicrotasks (<anonymous>)
> @apps/admin:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> @apps/admin:dev:  ELIFECYCLE  Command failed with exit code 1.
> @apps/admin:dev: ERROR: command finished with error: command (C:\Users\likui\IdeaProjects\vben3\apps\admin) pnpm run dev exited (1)
> @apps/admin#dev: command (C:\Users\likui\IdeaProjects\vben3\apps\admin) pnpm run dev exited (1)

问题出在以下代码
https://github.com/vbenjs/vben3/blob/c2fd46014002d00718328deb779e1d2ba89820f9/apps/admin/mock/demo/table.ts#L56

事实上是mock.js的问题
https://github.com/nuysoft/Mock/blob/c4d7cba01900b5c5bb8e3d474c8f5d07810ab72e/src/mock/random/image.js#L242-L251

### Reproduction

访问https://localhost:3000/#/demo/table/useTable可以重现

## System Info

- Operating System: win11
- Node version: v16.15.1
- Package manager (npm/yarn/pnpm) and version: pnpm 8.6.12

**Comment by adoin** [comment]
Hard to reproduce.
