### ISSUE TITLE
左侧菜单混合模式中，菜单不是显示在最顶层

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#209]
![image](https://github.com/vbenjs/vben3/assets/32682251/17029b67-cfac-4fdf-91e2-67629f39ef90)  
--
复现步骤;
1. 选择左侧菜单混合模式
2. 在设置中关闭固定展开菜单（默认关闭）
3. 打开树形表格页面

**Comment by likui628** [comment]
`vxe-tree--btn-wrapper `设置了z-index导致的
