### ISSUE TITLE
格式化插件配置vscode+webstorm

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#210]
为了避免格式化不一致导致的review困难，需要设定统一的格式化配置。

**Comment by wangjue666** [comment]
vben2的prettier格式化就行

**Comment by likui628** [comment]
我下午试一下webstorm，确定下格式化是否一致

**Comment by likui628** [comment]
![image](https://github.com/vbenjs/vben3/assets/90845831/98cb3aa3-d0f0-4844-a3a2-b765e115be04)
配置问题
