### ISSUE TITLE
顶部菜单模式Icon位置不居中

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#211]
导航栏模式为顶部菜单模式
![image](https://github.com/vbenjs/vben3/assets/90845831/ff127ec9-311a-4e0f-95d8-76e9c8367fdf)
菜单位置不居中
![image](https://github.com/vbenjs/vben3/assets/90845831/7137fae0-ed87-4892-b28b-61bb7f14a7a6)

**Comment by wangjue666** [comment]
![1698291796182](https://github.com/vbenjs/vben3/assets/24707417/d4b698fd-538c-4758-8f21-e1eacb4dbeba)

**Comment by wangjue666** [comment]
没有复现, 是不是你浏览器安装了一些扩展插件影响了样式

**Comment by aonoa** [comment]
我也没有复现

**Comment by aonoa** [comment]
看这个图，不止菜单位置不居中，logo位置还偏低了

**Comment by pzzyf** [comment]
![Uploading image.png…]()
是不是没适配mac

**Comment by pzzyf** [comment]
是不是没适配mac，mac上面看是复现的

**Comment by likui628** [comment]
重现不了了，先关闭了
