### ISSUE TITLE
标签页操作这里，关闭左右标签并没有按当前标签页的位置来变化

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#215]
标签页操作这里，关闭左右标签并没有按当前标签页的位置来变化
![image](https://github.com/vbenjs/vben3/assets/32682251/5df25c36-e417-4067-a742-66145fd569ad)

![image](https://github.com/vbenjs/vben3/assets/32682251/5a401945-6e96-4534-84db-b73b62e03a77)

比如这里选中的标签页在最左边，应该"关闭右侧标签页"允许点击，"关闭左侧标签页"置灰
当选中标签页在中间时，应该“关闭左、右侧标签页“都允许点击

**Comment by pzzyf** [comment]
<img width="1441" alt="image" src="https://github.com/vbenjs/vben3/assets/56245609/b77257c9-d4fe-420c-bf1b-520e5ee20c4b">

**Comment by pzzyf** [comment]
@aonoa

**Comment by aonoa** [comment]
> @aonoa

![image](https://github.com/vbenjs/vben3/assets/32682251/f943d727-2659-4ad6-ba6a-980300109db5)  
我一直不知道还可以在tab页上右键点击

**Comment by pzzyf** [comment]
https://github.com/vbenjs/vben3/pull/236 @aonoa

**Comment by pzzyf** [comment]
@aonoa  https://github.com/vbenjs/vben3/pull/236

**Comment by jinmao88** [comment]
修了

**Comment by jinmao88** [comment]
显示的问题修了  操作的逻辑可能有问题 你们测一下告诉我

**Comment by aonoa** [comment]
> 显示的问题修了 操作的逻辑可能有问题 你们测一下告诉我

右键非当前tab时会有问题
![image](https://github.com/vbenjs/vben3/assets/32682251/9ceb28d0-e973-40e2-b720-4c0e538666e6)
