### ISSUE TITLE
setting文件下的类型定义冲突

### ISSUE THREAD

**Issue by wangjue666** [vbenjs/vben3#220]
`packages/types/src/setting.ts` 下的许多interface即定义了 `hidden`又 定义了 `show` 字段, 是否重复了？

https://github.com/vbenjs/vben3/blob/eb3b7a29c419338ea93e4751c3173e720aec23b8/packages/types/src/setting.ts#L54

https://github.com/vbenjs/vben3/blob/eb3b7a29c419338ea93e4751c3173e720aec23b8/packages/types/src/setting.ts#L42

**Comment by likui628** [comment]
show比hidden合适，这个看来需要处理下
