### ISSUE TITLE
store里面的user爆红，再其他页面使用里面的方法使用不了

### ISSUE THREAD

**Issue by pzzyf** [vbenjs/vben3#224]
<img width="1512" alt="image" src="https://github.com/vbenjs/vben3/assets/56245609/67b3952e-ff39-44e7-8d79-c20f0d933df3">

**Comment by likui628** [comment]
跟这段代码有关系
```
 persist: {
    paths: ['userInfo', 'accessToken', 'roles'],
  },
```

**Comment by pzzyf** [comment]
看了，他那边持久化是正常使用的

**Comment by pzzyf** [comment]
<img width="306" alt="image" src="https://github.com/vbenjs/vben3/assets/56245609/d8519ed3-7a2f-4dd6-8a30-a5bab83c88a3">
<img width="423" alt="image" src="https://github.com/vbenjs/vben3/assets/56245609/065b5a16-7688-4517-8364-da32373db6e6">
<img width="936" alt="image" src="https://github.com/vbenjs/vben3/assets/56245609/018d120b-fc33-4a12-8d5b-18266406f682">

**Comment by adoin** [comment]
类型修复了，无法重现无法调用问题，比如lock-page组件试了 使用logout成功。
只修复类型的话 assign给我或者补充一下重现步骤？

**Comment by likui628** [comment]
https://github.com/vbenjs/vben3/pull/229
类型问题好了

**Comment by pzzyf** [comment]
报错是由于pinia.d.ts文件没用配置pinia库的类型声明 https://github.com/vbenjs/vben3/pull/229
