### ISSUE TITLE
The table instance has not been obtained yet, please make sure the table is presented when performing the table operation!

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vben3#233]
![image](https://github.com/vbenjs/vben3/assets/110399274/eb35e792-31d2-438e-a71a-15bacc41a382)
就是在modal里面新增时显示的是其中一个表格，编辑的时候显示的是另外一个表格，然后点开modal就报这个错误了

**Comment by likui628** [comment]
@zj1312114390 这个是vben2相关吧，请不要提交到vben3
