### ISSUE TITLE
路由设置showMenu: false无效

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#254]
![image](https://github.com/vbenjs/vben3/assets/32682251/0a511d0f-4e66-40f2-8e85-ee1a86735be8)
![image](https://github.com/vbenjs/vben3/assets/32682251/f4f49e44-e3d8-48c0-aae9-f69be4fd8d17)
设置showMenu: false后还是会显示

**Comment by likui628** [comment]
@aonoa 设置hideMenu，改好了
