### ISSUE TITLE
代码复用方案想法

### ISSUE THREAD

**Issue by cn-src** [vbenjs/vben3#266]
前端代码复用维护一直很头疼，特别是这种业务层的代码，但公司又是做很多交付型的项目，所以想着基于 vben 的多 package 这种合理的划分，想的一种复用方案（dw-pro 是内部维护的通用版名称）。

![yuque_diagram (4)](https://github.com/vbenjs/vben3/assets/8263180/ad91ce16-d660-4fbc-98a6-ceb9b9ccb293)

**Comment by likui628** [comment]
简单看了下，主要的目的是apps/admin内的业务代码的复用。这个跟vben3关系其实不大了。

**Comment by cn-src** [comment]
> 简单看了下，主要的目的是apps/admin内的业务代码的复用。这个跟vben3关系其实不大了。

跟 vben3 的 pakcage 拆分还是有一定关系的，复用代码的同时要保证能很好的同步开源仓库的代码，如果拆分的以及集成不够合理（比如循环引用），那就跟市面上的管理框架一样，每次一个新项目就是全量代码的复制，无论是更新合并什么的，维护代价极高。也就是说，下游的项目不能大的去变动 vben3 的代码和结构，这也就需要 vben3 考虑怎么合理的拆分结构了。

我觉得目前来说管理框架的最大痛点就是这个维护问题了，他无法像组件库那样复用，也无法做到 Umi 那样的应用层框架（这个学习成本也高），微前端技术也不是主要解决这个问题的。

目前来说，也就是合理的多 package 拆分（就像后端的多模块项目一样），然后在考虑更多的集成和扩展点。

**Comment by jinmao88** [comment]
个人的业务复用代码可以放在packages里 自己新建一个包即可

**Comment by baixjian** [comment]
> > 简单看了下，主要的目的是apps/admin内的业务代码的复用。这个跟vben3关系其实不大了。
> 
> 跟 vben3 的 pakcage 拆分还是有一定关系的，复用代码的同时要保证能很好的同步开源仓库的代码，如果拆分的以及集成不够合理（比如循环引用），那就跟市面上的管理框架一样，每次一个新项目就是全量代码的复制，无论是更新合并什么的，维护代价极高。也就是说，下游的项目不能大的去变动 vben3 的代码和结构，这也就需要 vben3 考虑怎么合理的拆分结构了。
> 
> 我觉得目前来说管理框架的最大痛点就是这个维护问题了，他无法像组件库那样复用，也无法做到 Umi 那样的应用层框架（这个学习成本也高），微前端技术也不是主要解决这个问题的。
> 
> 目前来说，也就是合理的多 package 拆分（就像后端的多模块项目一样），然后在考虑更多的集成和扩展点。

是不是理解为系统管理菜单跟业务菜单的解耦，有点类似于微前端的主/子应用。
