### ISSUE TITLE
添加 element-plus 模板

### ISSUE THREAD

**Issue by luoqiz** [vbenjs/vben3#295]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by pzzyf** [comment]
啥意思

**Comment by billkang** [comment]
使用element-plus，替换掉ant-design-vue。
我也很期待。ant-design-vue的文档，比element-plus差多了，不好用。element-plus市占率高很多

**Comment by DesignHhuang** [comment]
> 使用element-plus，替换掉ant-design-vue。 我也很期待。ant-design-vue的文档，比element-plus差多了，不好用。element-plus市占率高很多

这个项目没有规定使用哪个组件库，不存在替换的说法。它可以使用任何（或者多种）组件库组成VbenComponents。目前项目中示例使用的是Naive UI，开发者使用的时候可以换成任何组件库或者多种组件库。s

**Comment by pzzyf** [comment]
> > 使用element-plus，替换掉ant-design-vue。 我也很期待。ant-design-vue的文档，比element-plus差多了，不好用。element-plus市占率高很多
> 
> 这个项目没有规定使用哪个组件库，不存在替换的说法。它可以使用任何（或者多种）组件库组成VbenComponents。目前项目中示例使用的是Naive UI，开发者使用的时候可以换成任何组件库或者多种组件库。

不行吧，不同组件库对某一组件的属性的命名可能不一样，组件属性的类型定义不一样，比如Naive UI对form的size属性枚举值为'small' | 'medium' | 'large'，element-plus对size的枚举值是'' | 'large' | 'default' | 'small'，vben3基于navie ui搭建，封装的hooks，navie ui 有，ep没有，替换之后不就报错了吗

**Comment by DesignHhuang** [comment]
> > > 使用element-plus，替换掉ant-design-vue。 我也很期待。ant-design-vue的文档，比element-plus差多了，不好用。element-plus市占率高很多
> > 
> > 
> > 这个项目没有规定使用哪个组件库，不存在替换的说法。它可以使用任何（或者多种）组件库组成VbenComponents。目前项目中示例使用的是Naive UI，开发者使用的时候可以换成任何组件库或者多种组件库。
> 
> 不行吧，不同组件库对某一组件的属性的命名可能不一样，组件属性的类型定义不一样，比如Naive UI对form的size属性枚举值为'small' | 'medium' | 'large'，element-plus对size的枚举值是'' | 'large' | 'default' | 'small'，vben3基于navie ui搭建，封装的hooks，navie ui 有，ep没有，替换之后不就报错了吗

仔细研究一下源码，vben3 组件是做了个“胶水层”的，以达到不限制组件库

**Comment by pzzyf** [comment]
> > > > 使用element-plus，替换掉ant-design-vue。 我也很期待。ant-design-vue的文档，比element-plus差多了，不好用。element-plus市占率高很多
> > > 
> > > 
> > > 这个项目没有规定使用哪个组件库，不存在替换的说法。它可以使用任何（或者多种）组件库组成VbenComponents。目前项目中示例使用的是Naive UI，开发者使用的时候可以换成任何组件库或者多种组件库。
> > 
> > 
> > 不行吧，不同组件库对某一组件的属性的命名可能不一样，组件属性的类型定义不一样，比如Naive UI对form的size属性枚举值为'small' | 'medium' | 'large'，element-plus对size的枚举值是'' | 'large' | 'default' | 'small'，vben3基于navie ui搭建，封装的hooks，navie ui 有，ep没有，替换之后不就报错了吗
> 
> 仔细研究一下源码，vben3 组件是做了个“胶水层”的，以达到不限制组件库

封装的hooks用这个组件库的Attributes，换成另一个组件库，但是另一个组件库没有这个Attributes。组件库是可以替换的，hooks不得重新封装吗

**Comment by DesignHhuang** [comment]
> > > > > 使用element-plus，替换掉ant-design-vue。 我也很期待。ant-design-vue的文档，比element-plus差多了，不好用。element-plus市占率高很多
> > > > 
> > > > 
> > > > 这个项目没有规定使用哪个组件库，不存在替换的说法。它可以使用任何（或者多种）组件库组成VbenComponents。目前项目中示例使用的是Naive UI，开发者使用的时候可以换成任何组件库或者多种组件库。
> > > 
> > > 
> > > 不行吧，不同组件库对某一组件的属性的命名可能不一样，组件属性的类型定义不一样，比如Naive UI对form的size属性枚举值为'small' | 'medium' | 'large'，element-plus对size的枚举值是'' | 'large' | 'default' | 'small'，vben3基于navie ui搭建，封装的hooks，navie ui 有，ep没有，替换之后不就报错了吗
> > 
> > 
> > 仔细研究一下源码，vben3 组件是做了个“胶水层”的，以达到不限制组件库
> 
> 封装的hooks用这个组件库的Attributes，换成另一个组件库，但是另一个组件库没有这个Attributes。组件库是可以替换的，hooks不得重新封装吗

packages中hooks应该不会带组件的Attributes吧，单独项目中的可能需要

**Comment by jinmao88** [comment]
组件本身的参数和方法 需要自己调整的

**Comment by sincely** [comment]
element-plus就是一个垃圾，能和ant-design-vue比？
