### ISSUE TITLE
侧边栏和顶栏背景色

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#299]
侧边栏和顶栏采用themeOverrides的方式设置下背景色。

**Comment by likui628** [comment]
https://github.com/vbenjs/vben3/pull/302
侧边栏，顶栏做背景色可以看上面PR的方案。

但是有个问题，大多数的组件库侧边栏什么的其实只支持浅色和暗色切换的。

是不是将之前的侧边栏和顶栏的背景色设置的代码清除掉
@jinmao88

**Comment by jinmao88** [comment]
需要删的 我写了todo 之前模式有遗留的东西
