### ISSUE TITLE
nodejs-v20-lts 运行报错： socket hang up

### ISSUE THREAD

**Issue by billkang** [vbenjs/vben3#317]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

使用nodejs-v20-lts运行项目，报错：socket hang up

### 复现 Bug

![微信图片_20231225170357](https://github.com/vbenjs/vben3/assets/3007316/f0f1659e-68b4-41f8-833c-13fe78db4a41)

## 系统信息

- 操作系统: windows11
- Node 版本:  v20.10.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.12.1

**Comment by DesignHhuang** [comment]
看一下你的.env.dev配置，确定你的代码是最新的么？

**Comment by jinmao88** [comment]
端口被占用了吧

**Comment by billkang** [comment]
嗯，应该是端口被占用了。现在可以正常运行
