### ISSUE TITLE
VbenComponent 能否添加类似于饿了么的<el-link> 组件？

### ISSUE THREAD

**Issue by GitACDreamer** [vbenjs/vben3#42]
### Subject of the feature
https://element-plus.org/zh-CN/component/link.html
Describe your issue here.
![image](https://user-images.githubusercontent.com/19402747/217481704-c88f42b0-de8d-4d1b-9640-efae90d85ba0.png)

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by jinmao88** [comment]
可以
