### ISSUE TITLE
本地上传可以，打包到生产后，报如下错误，不知道有人是否遇到

### ISSUE THREAD

**Issue by wskiawv** [vbenjs/vben3#45]
TypeError: Cannot read properties of undefined (reading 'data') at responseInterceptorsCatch

**Comment by wskiawv** [comment]
<BasicUpload :maxSize="10" :maxNumber="1" @change="handleChange" :emptyHidePreview="true" :api="uploadApi" />

export function uploadApi(
    params: UploadFileParams,
    onUploadProgress: (progressEvent: ProgressEvent) => void
  ) {
    return defHttp.uploadFile<UploadApiResult>(
      {
        url: Api.importExcel,
        onUploadProgress
      },
      params
    )
}

**Comment by jinmao88** [comment]
看不懂

**Comment by wskiawv** [comment]
已解决，关闭mock即可
