### ISSUE TITLE
使用360浏览器启动项目报错

### ISSUE THREAD

**Issue by flyrun9527** [vbenjs/vben3#49]
Uncaught SyntaxError: Unexpected reserved word
![image](https://user-images.githubusercontent.com/66985784/219964937-7ab73325-07ad-4ab8-a227-efed9eb96193.png)
![image](https://user-images.githubusercontent.com/66985784/219964950-96bf6633-c4ec-44c4-b86f-dc83dc6ab3b1.png)

卡在加载进度条这个页面

**Comment by flyrun9527** [comment]
尝试 谷歌和edge浏览器正常

**Comment by jinmao88** [comment]
360内核太老了好像
