### ISSUE TITLE
vben3是否会将components下的组件单独抽离成组件库进行维护？

### ISSUE THREAD

**Issue by x-thence** [vbenjs/vben3#50]
如题，想问下是大佬否有这个计划呢，是否有相关的日期表

**Comment by jinmao88** [comment]
你说的是什么组件？

**Comment by x-thence** [comment]
> 

components下的所有组件抽成npm包的组件库

**Comment by luqizheng** [comment]
> > 
> 
> components下的所有组件抽成npm包的组件库

赞成，这样我可以在业务组件引用。
