### ISSUE TITLE
希望可以使用element作为ui库，而不是ant design vue

### ISSUE THREAD

**Issue by 314171441** [vbenjs/vben3#60]
### 希望可以使用element作为ui库

希望可以使用element作为ui库，而不是ant design vue。 
因为ant design vue 在实际生产中功能表现过于单一。

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by jinmao88** [comment]
不限制组件库了
