### ISSUE TITLE
代码不做修改build报错,运行正常

### ISSUE THREAD

**Issue by zxuanhong** [vbenjs/vben3#75]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
1. 不做任何修改，运行正常，但是打包错误(不管是npm run build 还是npm run turbo:build)
<img width="1272" alt="image" src="https://github.com/vbenjs/vben3/assets/62740686/5e220ccc-2c92-44f2-8b44-1ce013dfb6e9">
2. 运行成功截图
<img width="1585" alt="image" src="https://github.com/vbenjs/vben3/assets/62740686/6accf3e7-b18d-4437-b27a-ba2036766cc9">

## System Info

- Operating System: mac
- Node version: v16.20.0
- Package manager (npm/yarn/pnpm) and version: pnpm 8.4.0

**Comment by jinmao88** [comment]
看看编译的时候哪里报错

**Comment by zxuanhong** [comment]
> 看看编译的时候哪里报错
@jinmao88 
大佬你那边正常吗？？我运行没问题的，就是打包已报错。看好像是编码问题，但是没找到问题所在。错误的地方就截图的东西。其他都是没有报错的

**Comment by jinmao88** [comment]
![image](https://github.com/vbenjs/vben3/assets/50581550/13281493-fde7-40ae-a7ec-762003569d59)
