### ISSUE TITLE
打包后报错： TypeError: Cannot destructure property 'currentRoute' of 't' as it is undefined.

### ISSUE THREAD

**Issue by MaYaQ** [vbenjs/vben3#83]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

将项目打包后进行preview，登录后页面空白，控制台报错：TypeError: Cannot destructure property 'currentRoute' of 't' as it is undefined.

### 复现 Bug

拉取main分支 ，可以直接复现

## 系统信息

- 操作系统:
- Node 版本:18.16.1
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm :7.17.0

**Comment by aonoa** [comment]
这个问题与 https://github.com/vbenjs/vben3/issues/81 应该是一样的，还在重构
