### ISSUE TITLE
右上角头像、设置那些没了

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#86]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

![image](https://github.com/vbenjs/vben3/assets/32682251/1100954b-1796-487e-b9a5-7fc070f9709f) 

应该是这样： 
![image](https://github.com/vbenjs/vben3/assets/32682251/063639ab-910f-4754-8295-0336af60910d)

### 复现 Bug

拉取最新代码运行

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by likui628** [comment]
这个知道原因了

以下代码导致appConfigOptions的类型解析有问题
```
  const appConfigOptions = storeToRefs(
    useAppConfigStore as StoreGeneric,
  ) as unknown as DefineAppConfigOptions & DefineAppConfigStoreGetters
```
实际上configStore.header是一个Ref，需要加个value
```
  const getShowHeader = computed(() => configStore.header.show)
```

**Comment by likui628** [comment]
@aonoa 可以显示了
![image](https://github.com/vbenjs/vben3/assets/90845831/3b3d6df4-0ee7-42ea-9367-d0c4f9c6b785)

**Comment by aonoa** [comment]
> @aonoa 可以显示了 ![image](https://user-images.githubusercontent.com/90845831/266556738-3b3d6df4-0ee7-42ea-9367-d0c4f9c6b785.png)

泰酷辣

**Comment by likui628** [comment]
是的，还需要进一步处理

**Comment by likui628** [comment]
> 好像还缺少设置按钮

#88 改了
