### ISSUE TITLE
除了导航栏模式为"顶部菜单栏模式",其他模式下鼠标移动到导航栏会报错

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vben3#93]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

除了导航栏模式为"顶部菜单栏模式",其他模式下鼠标移动到导航栏会报错
![image](https://github.com/vbenjs/vben3/assets/32682251/595c1125-67d6-4c09-8f21-ad9f120190a7) 
![image](https://github.com/vbenjs/vben3/assets/32682251/044d2f8f-c0bf-4617-9486-80403d106f95) 

### 复现 Bug

拉取最新代码并运行

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by aonoa** [comment]
修改后在我本地没有问题,但是在演示站 https://vben.mufei88.com/ 上还是有问题,看Actions好像也成功部署了,不知道为啥

**Comment by likui628** [comment]
本地可以就行了，应该是同步的问题

**Comment by likui628** [comment]
> 修改后在我本地没有问题,但是在演示站 https://vben.mufei88.com/ 上还是有问题,看Actions好像也成功部署了,不知道为啥

你再试一下，应该是可以了
